### ISSUE TITLE
Prevelika količina sporočil pri neuspešnem postavljanju SL ukaza

### ISSUE THREAD

**Issue by PeterVeliki** [PeterVeliki/M5#6]
Težava trenutnega algoritma je, da v primeru, ko postavljanje stop loss ukaza ne uspe, nima implementiranega pravega mehanizma za obravnavo napake, temveč enostavno pošlje sporočilo na mobilni telefon, da nastavljanje stop loss ukaza ni bilo uspešno, nato pa dogajanje prepusti človeku.

Ker cena precej skače, lahko tudi zelo hitro skoči navzgor ali navzdol, se občasno zgodi, da algoritmu ne uspe pravočasno nastaviti stop loss ukazov. Če človek nima časa, da bi čakal in spremljal kdaj bo cena ponovno primerna, so lahko zaradi tega izgube algoritma po nepotrebnem večje.

Sistem za bolj inteligentno obravnavanje neuspešnih nastavitev stop loss ukazov, bi deloval tako, kot je opisano v nadaljevanju.

Uvedemo naslednje nove podatkovne strukture: 

- polje `slVrsta`;
- globalna spremenljivka `kslVrsta`.

Uvedemo naslednje nove funkcije:

- `PreveriSL` - periodično preverja ali je SL mogoče nastaviti;
- `DodajVVrsto` - doda id pozicije v polje `slVrsta`;
- `OdstranIzVrste` - odstrani id pozicije iz polja `slVrsta`;

V polju hranimo ID-je vseh pozicij, pri katerih postavljanje stop loss ukazov ni bilo uspešno, globalna spremenljivka pa vedno kaže naslednje prosto mesto v polju `slVrsta`.

1. nastavljanje stop loss ukazov bi se prožilo znotraj funkcij za stanja, tako kot sedaj.
2. znotraj funkcij za stanja vpeljemo novo lokalno spremenljivko, v katero shranimo rezultat nastavljanja stop loss ukaza.
3. Nato testiramo vrednost spremenljivke ali je bilo nastavljanje ukaza uspešno ali ne. V primeru, da je bilo nastavljanje ukaza uspešno, potem je vse v redu in ni potrebna nobena posebna obravnava. V primeru, da nastavljanje ukaza ni bilo uspešno, nadaljujemo v naslednji točki.
4. ID ukaza (na primer 34232) dodamo v polje `slVrsta` s klicem funkcije `DodajVVrsto`
5. s klicem nove funkcije `PreveriSL` znotraj funkcije start, ob vsaki spremembi cene preverimo ali je katerega od stop loss ukazov že mogoče realizirati - v tem primeru poskusimo s ponovnim klicem funkcije `PostaviSL`. V primeru, da je katera od pozicij v vrsti zaprta, jo iz vrste odstranimo s klicem funkcije `OdstraniIzVrste`.

Narediti je potrebno naslednje:

- [x] dodati zgoraj naštete podatkovne strukture med globalne spremenljivke algoritma;
- [x] dopolniti obravnavanje napak v funkciji `S2Nakup`, podrobnosti so opisane v #7 ;
- [x] dopolniti obravnavanje napak v funkciji `S3Prodaja`, podrobnosti so opisane v #7 ;
- [x] napisati funkcijo `PreveriSL`, podrobnosti so opisane v #9 ;
- [x] napisati funkcijo `DodajVVrsto`, podrobnosti so opisane v #10;
- [x] napisati funkcijo `OdstraniIzVrste`, podrobnosti so opisane v #11 ;
- [x] dopolniti funkcijo `start` s klicem funkcije `PreveriSL`;
- [x] v funkciji `PostaviSL` izključiti pošiljanje sporočil;
- [x] poostreno spremljati delovanje prvi dan po objavi.

**Comment by PeterVeliki** [comment]
Implementirano z verzijo 4.
